# Generated by Django 3.1 on 2020-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tecnologies',
            field=models.ManyToManyField(blank=True, default='', to='portfolio.Tecnology', verbose_name='Tecnologies'),
        ),
    ]
