# Generated by Django 3.1 on 2020-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200825_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tecnology',
            new_name='Technology',
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['-created'], 'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='tecnologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, default='', to='portfolio.Technology', verbose_name='Tecnologies'),
        ),
    ]
