# Generated by Django 3.1 on 2020-08-25 23:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200825_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, default='', verbose_name='Github Link'),
        ),
        migrations.AddField(
            model_name='project',
            name='web_link',
            field=models.URLField(blank=True, default='', verbose_name='Web Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Description'),
        ),
    ]
